force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Opportunity__c/Course_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Course Opportunity</label>
    <nameField>
        <label>Course Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Opportunity__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.Instructor__c</field>
            <operation>equals</operation>
            <valueField>$Source.Instuctor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Opportunities</relationshipLabel>
    <relationshipName>Course_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Start_Date__c  +  Course__r.Length__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/fields/Instuctor__c.field-meta.xml
<CustomField>
    <fullName>Instuctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instuctor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourseOpportunityHandler.cls
public with sharing class CourseOpportunityHandler {
    public static void newCalendarEvent(List<Course_Opportunity__c> courses) {
        List<Event> newEvent = new List<Event>();
        Boolean eventExist = false;
         List<Event> existing = [SELECT WhatID FROM Event];
        for(Course_Opportunity__c o : courses){
           eventExist = false;
            for(Integer i = 0; i<existing.size();i++){
                if(existing[i].whatId ==o.Id){
                    eventExist = true;
                }
            }
            if(!eventExist){
                Event eve = new Event();
                eve.WhatId = o.Id;
                eve.StartDateTime = o.Start_Date__c;
                eve.EndDateTime = o.End_Date__c ;
                eve.Subject = o.Name + ' : ' + o.Course__c;
                eve.OwnerId = o.Instuctor__c;
                eve.Location = o.Location__c;
                
                newEvent.add(eve);
            }
        }
        insert newEvent;
    }
    public static void updateCalendarEvent(List<Course_Opportunity__c> courses) {
        List<Event> newEvent = new List<Event>();
        Boolean eventExist;
        List<Event> existing = [SELECT WhatID FROM Event]; 
        for(Course_Opportunity__c o : courses){
              eventExist = false;
              for(Integer i=0; i>= existing.size();i++)
            if(!eventExist ){
                existing[i].WhatId = o.Id;
                existing[i].StartDateTime = o.Start_Date__c;
                existing[i].EndDateTime = o.End_Date__c ;
                existing[i].Subject = o.Name + ' : ' + o.Course__c;
                existing[i].OwnerId = o.Instuctor__c;
                existing[i].Location = o.Location__c;
                newEvent.add(existing[i]);
            }
        }
        update newEvent;
    }
    public static void deleteCalendarEvent(List<Course_Opportunity__c> courses) {
        List<Event> newEvent = new List<Event>();
        List<Event> existing = [SELECT WhatID FROM Event];

        for(Course_Opportunity__c o : courses){
            if(existing.size() > 0  && o.Stage__c == 'Cancelled'){
                delete[SELECT WhatID FROM Event WHERE WhatId =: o.id];
                
            }
        }
        
    }
}