force-app/main/default/objects/Course_Invoice__c/Course_Invoice__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Service Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Invoice__c/fields/Course_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Course_Opportunity__c</fullName>
    <label>Course Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course_Opportunity__c.Instuctor__c</field>
            <operation>equals</operation>
            <valueField>$Source.Instructor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course_Opportunity__c</referenceTo>
    <relationshipLabel>Course Invoices</relationshipLabel>
    <relationshipName>Service_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Invoice__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Invoice__c/fields/Retention__c.field-meta.xml
<CustomField>
    <fullName>Retention__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Retention</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Invoice__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/Course_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Course Opportunity</label>
    <nameField>
        <label>Course Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Opportunity__c/fields/Instuctor__c.field-meta.xml
<CustomField>
    <fullName>Instuctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instuctor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceInvoiceGenerator.cls
    public with sharing class ServiceInvoiceGenerator {
        public static void ServiceInvoiceGenerator(List<Course_Opportunity__c> courses, List<Course_Opportunity__c> oldCourses) {
        List<Course_Invoice__c> newInvoices = new List<Course_Invoice__c>();
        Integer i = 0;
            for(Course_Opportunity__c o : courses){
                if(o.Stage__c == 'Completed' && oldCourses[i].Stage__c != 'Completed'){
                    Course_Invoice__c newInv = new Course_Invoice__c();
                    newInv.Instructor__c = o.Instuctor__c;
                    newInv.Course_Opportunity__c = o.Id;
                    newInv.Status__c = 'Draft';
                    newInv.Retention__c = 30;
                    newInv.VAT__c = 20;
                    newInvoices.add(newInv);

                }
                i++;
            }
            insert newInvoices;
        }
    }