force-app/main/default/objects/Course_Invoice__c/Course_Invoice__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Service Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Invoice__c/fields/Course_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Course_Opportunity__c</fullName>
    <label>Course Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course_Opportunity__c.Instuctor__c</field>
            <operation>equals</operation>
            <valueField>$Source.Instructor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course_Opportunity__c</referenceTo>
    <relationshipLabel>Course Invoices</relationshipLabel>
    <relationshipName>Service_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Opportunity__c/Course_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Course Opportunity</label>
    <nameField>
        <label>Course Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Course_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Course_Invoice__c</fullName>
    <label>Course Invoice</label>
    <referenceTo>Course_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CloneInvoiceController.cls
public with sharing class CloneInvoiceController {   
//     public String idOfRecord {get;set;}
   
//     public void cloneRecord()
//     {
//         List<Invoice_Line_Item__c> items = new List<Invoice_Line_Item__c>();
//         Course_Invoice__c inv = [SELECT Id, Name, Stage__c, Course_Opportunity__c FROM Course_Invoice__c WHERE Id = idOfRecord ];
//         Course_Invoice__c invCopy = inv.clone(false, true);
//         insert invCopy;
//         List<Invoice_Line_Item__c> it = [SELECT Id, Name, Course_Invoice__c FROM Invoice_Line_Item__c WHERE Course_Invoice__c = : inv.Id];
//         for(Invoice_Line_Item__c i : it)
//         {
//             Invoice_Line_Item__c itCopy = i.clone(false,true);
//             itCopy.Course_Invoice__c = invCopy.Id;
//             items.add(itCopy);
//         }
//         insert items;
//     }
}